
public enum MOVE_PATTERN
{
    NORTH, NORTH_NO_KILL, SOUTH, SOUTH_NO_KILL, DIAGONAL_ON_ENEMY_NORTH, DIAGONAL_ON_ENEMY_SOUTH,
    TWO_INITIALLY_NORTH, TWO_INITIALLY_SOUTH, UNRESTRICTED_NORTH, UNRESTRICTED_EAST,
    UNRESTRICTED_SOUTH, UNRESTRICTED_WEST, UNRESTRICTED_NORTH_EAST, UNRESTRICTED_NORTH_WEST,
    UNRESTRICTED_SOUTH_EAST, UNRESTRICTED_SOUTH_WEST, L_SHAPE, ONE_ANYWHERE;
}

