
public enum MOVE_PATTERN
{
    UP, DOWN, DIAGONAL_ON_ENEMY, TWO_INITIALLY, UNRESTRICTED_NORTH, UNRESTRICTED_EAST,
    UNRESTRICTED_SOUTH, UNRESTRICTED_WEST, UNRESTRICTED_NORTH_EAST, UNRESTRICTED_NORTH_WEST,
    UNRESTRICTED_SOUTH_EAST, UNRESTRICTED_SOUTH_WEST;
}

